### ISSUE TITLE
Qual a motivação desse projeto?

### ISSUE THREAD

**Issue by marcieltorres** [yurizp/payments-management#5]
@yurizp não encontrei a descrição detalhada no `readme` :eyes: qual é o objetivo desse projeto?

**Comment by yurizp** [comment]
@marcieltorres chegou a dar um arrepio quado li no e-mail, saudades do 👮  Celso.
Vou botar Celsera.

**Comment by marcieltorres** [comment]
Valeu @yurizp :heart:
